apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: ameenpt/medicure-app:latest
        ports:
        - containerPort: 8080
